name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rustup with the given info
      uses: brndnmtthws/rust-action-rustup@v1.0.0
      with:  
        toolchain: 'nightly-2023-03-05'
        components: rust-src
        allow-downgrade: true  
        targets: x86_64-pc-windows-msvc
          
    - name: Build
      run: |
        rustup default nightly
        cargo install cargo-psp
        rustup run nightly-2023-03-05 cargo psp
