name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Add nightly tc
      uses: brndnmtthws/rust-action-rustup@v1.0.0
      with:
        toolchain: 'nightly'
    - name: Install Cargo PSP
      uses: actions-rs/cargo@v1
      with:
        command: install
        toolchain: nightly
        args: cargo-psp
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: psp
        args: --no-workspace workspace-ci-flow
    
