name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_MAKE_RUN_CODECOV: true

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rustup with the given info
      uses: brndnmtthws/rust-action-rustup@v1.0.0
      with:  
        toolchain: 'nightly-2024-03-05'
        components: rust-src
        allow-downgrade: true  
        targets: x86_64-pc-windows-msvc
    - name: Add nightly tc
      uses: brndnmtthws/rust-action-rustup@v1.0.0
      with:
        toolchain: 'nightly'
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Install Cargo PSP
      uses: actions-rs/cargo@v1
      with:
        command: install
        toolchain: nightly
        args: cargo-psp
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        command: make psp
        args: --no-workspace workspace-ci-flow
    
